# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Test


on:
  pull_request:
    branches: [ main ]    # main 브랜치에 PR 보낼 때 실행

jobs:
  test:
    runs-on: ubuntu-20.04
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # JDK Setup
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

        # Gradle Wrapper 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

        # Gradle Test를 실행한다
      - name: Test with Gradle
        run: ./gradlew --info test

        # Test 후 Report 생성
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: '**/build/test-results/test/TEST-*.xml'
